# fly.toml app configuration file generated for discover-lab on 2023-07-06T01:22:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discover-lab"
primary_region = "eze"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = "start.sh"
  entrypoint = "sh"

[mounts]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
